### ISSUE TITLE
Open links in a new tab

### ISSUE THREAD

**Issue by Diddyy** [tightenco/novapackages-issues#12]
All the links around the site to external sites currently open in the same tab which is annoying when I look at a package. For example when I want to inspect a packages code I click a link on the side to go to their github or even click any link in the readme to find out more about the package and it opens in my current tab.

Would make for a better (In my opinion) user experience if you could change this :)
Thanks! 👍

**Comment by mattstauffer** [comment]
In general, we try to avoid `target="_blank"` as it has a few problems with it. You can read about a couple here: https://css-tricks.com/use-target_blank/

As such, we tend to just allow our users to develop the habit of cmd-click/ctrl-click-ing our sites.

I totally feel your pain. I wish there were better solutions all-around. :)
