### ISSUE TITLE
Although mostly about packages, is this app allowed?

### ISSUE THREAD

**Issue by bbrala** [tightenco/novapackages-issues#13]
I feel people who use Nova could really use this, but technically it isn't a package, so i wonder, would you allow this on the site?

https://github.com/swisnl/laravel-nova-mirror

This application enables you to update a private mirror of Laravel Nova automatically. It downloads releases from the Nova site and updates a repository with the correct releases.

**Comment by mattstauffer** [comment]
Sure!
