### ISSUE TITLE
Twitter profile & automatic new package tweet

### ISSUE THREAD

**Issue by dillingham** [tightenco/novapackages-issues#15]

**Comment by mattstauffer** [comment]
The only significant technical challenge I can think of is that we would have to figure out

A) how avoid people using it to be shitty and spam, and
B) how to handle draft packages (do we add a note saying "hey if you create this package as a draft you just won't get a tweet"? do we listen for the first time they ever move it from draft to non-draft and tweet then (ugh sounds gross)? something else?

We already got the handle: https://twitter.com/novapackages

And we already have the notifications built... just need to figure these issues out.

**Comment by dillingham** [comment]
Maybe “A tweet to promote this package will go live 24hrs after it is published” 

Let’s people edit as draft and avoids spam, as an opportunity to inspect is presented. Also removes the incentive if spammers know it isn’t immediate and reviewed.

**Comment by mattstauffer** [comment]
I think thats a great idea. It still would require us to decide how to handle packages that spend a long time as a draft but I’m ok with leaving that to be decided when we implement it. The Approval queue idea is more complicated and requires more work on our part but it potentially alleviates the spam issue, like you’re saying.

I’ll think about it a bit and then we will likely do something like this. Thanks!

**Comment by vootrunner** [comment]
@mattstauffer - set a time limit on draft status and when it expires, drop the unpublished entry, or set it to a zombie status that is ignored and requires manual intervention from the submitter to move back to draft status. I can't imagine a valid reason to have a package in draft status for an unlimited period of time.

- Sam

**Comment by mattstauffer** [comment]
Yah, I think the broader question here is about draft status. How people use it, whether it's useful now that Nova is published, etc.

**Comment by dillingham** [comment]
As far as the feature goes, it just needs a published_at timestamp and a chron that checks every hour for any packages published 24 hours ago. Draft status seems unrelated as it is regarding promoting published packages.

**Comment by mattstauffer** [comment]
@dillingham What happens if someone publishes and then unpublishes a package? It'll get tweeted multiple times. Then you have to add a tweeted_at property or another place where these sorts of things are tracked. All simple enough but adding increasingly levels of complexity for what feels like a simple feature.

**Comment by vootrunner** [comment]
I've been under the impression that drafts were used as a method to pre-stage a package with a future "go live" date so that the maintainer have an announcement day. If that's not the case, then I don't think drafts are worth the hassle.

**Comment by dillingham** [comment]
Matt, only let publish once.

**Comment by mattstauffer** [comment]
@dillingham I agree; but that's more technical complexity. :) Some of the complexity on these issues are decisions we have to make; some of them are code we need to write and architecture we need to introduce and every such piece of code and/or architecture are now technical debt that need to be maintained.

What I am assessing is whether the cost of maintaining a Tweeting system that handles the complexity of the current draft system is worth it; and, if not, what changes we need to make to ensure it all works well given our decisions.

**Comment by dillingham** [comment]
Make a microservice that checks the rss

Last suggestion, I’m chiming out :)

**Comment by mattstauffer** [comment]
@dillingham Haha, that's also possible, but runs into all the same problems. Please trust me: If I spend as much time deciding what to do with drafts as we have spent going around on ideas here, we'll fix the draft issue and then implement this feature. Thank you for your suggestions! <3

**Comment by mattstauffer** [comment]
We're dropping drafts, so this can now be up on our list again. :)
