### ISSUE TITLE
Popular Packages Section

### ISSUE THREAD

**Issue by SL0wZEr** [tightenco/novapackages-issues#17]
I see that the popular packages haven’t changed since they’ve been “added” to the website, I’m not sure but I always see this as a not so good thing especially if it is visible above the fold.

I suggest that you either put the recent packages at the top or you change the functionality of the popular packages to something like “Today’s popular packages” or so.

**Comment by mattstauffer** [comment]
The popular packages right now is github_stars (times a magic multiplier) + packagist_downloads (times a magic multiplier). We will be adding ratings soon. When we have more time we'll likely add something like "popular recently" vs "popular all-time".

**Comment by SL0wZEr** [comment]
My point was more about the user experience. At the moment when someone revisits the website, he will see the same "old" packages he saw before. That's why I suggested moving the **Recent Packages** section to the top, before the **Popular Packages** section :D

**Comment by mattstauffer** [comment]
@SL0wZEr Yep, I got it. :) Thanks! I understood your suggestion, but I had no feedback there; I think it's a good idea and I've been considering it for a while and it'll likely happen. However, I did have feedback on the popular section feeling old, so I gave that. Thanks again!
