### ISSUE TITLE
Editing Packages

### ISSUE THREAD

**Issue by vmitchell85** [tightenco/novapackages-issues#2]
Forgot to add an image to the package description... doesn't look like there is any way to edit them.

**Comment by mattstauffer** [comment]
You can edit any package for which you are an author.

This is true for any of your collaborators you maintain.

So  I maintain the `mattstauffer` collaborator and the `tightenco` collaborator and therefore I can edit any packages that are authored by either of those collaborators.

<img width="575" alt="image" src="https://user-images.githubusercontent.com/151829/44622289-bb382080-a883-11e8-9098-14cbf3301091.png">

**Comment by mattstauffer** [comment]
That said.. I just found a bug on the edit package page that I must've introduced yesterday. I'll fix it ASAP. 😬

**Comment by vmitchell85** [comment]
Ahh.. was looking for a link on the package page

**Comment by vmitchell85** [comment]
I presume you mean this: 
![image](https://user-images.githubusercontent.com/1248035/44622301-e4f14780-a883-11e8-9b1b-4c9a56d6b0ec.png)

**Comment by mattstauffer** [comment]
Fixed now.
