### ISSUE TITLE
Recent Packages Feed Update Trigger

### ISSUE THREAD

**Issue by marktopper** [tightenco/novapackages-issues#22]
Hi, I am using Slack to subscribe to `Recent Packages` RSS feed.
However, it seems that it triggers a new item when a package is updated, is that meant to be like that?

If so, would there be a way to have a feed that doesn't re-trigger an item on update?

**Comment by mattstauffer** [comment]
It’s not on purpose. I bet I just copied the setup code wrong and it pulls updated at instead of created at. I’ll take a look as soon as I can.

**Comment by mattstauffer** [comment]
@marktopper I took a look, and the RSS feed just grabs the latest twenty `created_at`, which shouldn't change the list based on `updated_at`. However, it *does* pass an `updated` parameter, which will be updated. Maybe Slack watches that key? One thing I guess would be possible if that's the case is to set that `updated` property to just the `created_at` but that seems kinda weird. I'm curious what the desired behavior is here, to be honest.

**Comment by marktopper** [comment]
I see, I will take a quick talk with Slack on the issue and get back :)

**Comment by marktopper** [comment]
Slack says that they has issues with their RSS reader.
Thanks for checking it out though.

**Comment by mattstauffer** [comment]
@marktopper ahh, great to hear--thanks! :)
