### ISSUE TITLE
Package won't update

### ISSUE THREAD

**Issue by NikolaySav** [tightenco/novapackages-issues#23]
Greetings!

I've submitted a package and modified it later on github and packagist.
But at novapackages.com it doesn't update (version, description etc).

https://novapackages.com/packages/nsavinov/nova-json-schema-field

Should i initiate a manual update or what is the autorefresh time?

Thanks.

**Comment by NikolaySav** [comment]
after 20 hours it was automatically updated.
Closing issue.

**Comment by manogi** [comment]
Hi everyone - I don't want to open a new issue for this, but could that be refreshed a bit more often? may be like every 15 mins or so? That would be awesome!

**Comment by mattstauffer** [comment]
@manogi Could you open an new issue and describe what pain point you're experiencing? Thanks!
