### ISSUE TITLE
Make tags clickable on Package Detail Page

### ISSUE THREAD

**Issue by king724** [tightenco/novapackages-issues#24]
On the right sidebar within a package detail page, the tags can't be clicked on (like you can on the homepage). I think it would be great if you could click on them and it would send you to the filtered home screen.

Unclickable tags in question:
<img width="393" alt="screenshot 2018-09-10 00 36 40" src="https://user-images.githubusercontent.com/350488/45283046-a073c780-b491-11e8-8c63-018a3524734c.png">

Desired result from clicking on the 'backup' tag:
<img width="719" alt="screenshot 2018-09-10 00 36 46" src="https://user-images.githubusercontent.com/350488/45283096-c7ca9480-b491-11e8-81c4-e2b219cec3d3.png">

Thank you!

**Comment by king724** [comment]
This seems to be added with other enhancements. Thank you!

**Comment by sariyana** [comment]
Sorry, I forgot to close this one, but yes it's taken care of. Thanks for your help, @king724!
