### ISSUE TITLE
Filters are forgotten

### ISSUE THREAD

**Issue by king724** [tightenco/novapackages-issues#25]
After selecting a filter (or tag) on the homepage, clicking to view a package, then hitting browser back button removes the filter.

**Steps to reproduce** 
1. Load [novapackages.com](https://novapackages.com)
1. Click 'card' filter. 
1. Click on Google Analytics card
1. Click back in the browser 

**Current Result**
Get redirected back to unfiltered homepage.

**Desired result** 
Get sent back to the package listing with it filtered by 'card' so I can continue browsing other cards.

Thank you!

**Comment by manogi** [comment]
Would like to add that it is also the "<- back" Link in the upper left corner which has the same "problem", as it also does not lead to the filtered homepage. I just get started with Nova, so I click "All Packages" a lot, then scroll down and click on some card. The desired (and "learned") effect would be to land on the homepage with all Packages at the scroll position where I was before (at least with the native browser back button).

**Comment by mattstauffer** [comment]
Totally agreed! Thanks for this feedback; it's 100% on our list!

**Comment by sariyana** [comment]
This is in and should be good to go! Let us know if there are any questions!

**Comment by manogi** [comment]
Thanks for the improvement - it's still not working when selecting "All Packages", though. After the jump back I'm in "Poupular & Recent" again.

**Comment by sariyana** [comment]
Thanks for letting us know. We’ll get that fixed as soon as possible!

**Comment by sariyana** [comment]
Alrighty, we should be all set now! The "all packages" filter should be working correctly now.
