### ISSUE TITLE
Open API beyond recent and popular

### ISSUE THREAD

**Issue by chris-ware** [tightenco/novapackages-issues#28]
It's be great to be able to query the API to get a list of all the available packages, not just the most recent and most popular. I can't see any ability to be able to do this, so thought I'd suggest it as I would definitely make use of it.

**Comment by mattstauffer** [comment]
@chris-ware Thanks! Could you give some examples? One thing we might do is make a more robust API available but only behind API keys--which means it couldn't be used in packages. Whether you're interested in using this in a package or in your own app would have an impact on how we approached the best solution.

Thanks!

**Comment by chris-ware** [comment]
@mattstauffer 
So, I'm creating a small system that tracks nova packages and creates a daily email of new, popular and recently updated packages. This is because myself and several of my colleagues spend far too long browsing the site checking for new packages. Whilst the recent and popular APIs cover this, it does mean that if there is a sporadic influx of packages, I may miss some if the collection command isn't run often enough. Having an API key in place is perfectly acceptable for my use case.

**Comment by mattstauffer** [comment]
@chris-ware What endpoints would you most like to use for something like this? And are there any requests outside of the API that we could help you with to make it easier for you to discover new packages?

**Comment by chris-ware** [comment]
@mattstauffer Just the ability to be able to get all the packages, even if it were paginated and limited, just to be able to collate them would be grand.

**Comment by mattstauffer** [comment]
@chris-ware You still building this? Finally getting to my emails.

**Comment by chris-ware** [comment]
@mattstaufer I have actually got most of my small system built for this. For legacy packages, I managed to get most of what I needed from the Nova Packages site itself, but it would be great to be able to get it all via API.

**Comment by mattstauffer** [comment]
@chris-ware OK, it's up. It's behind API auth, so you'll have to set up a Passport token here: https://novapackages.com/app/api
