### ISSUE TITLE
Package Creator Link

### ISSUE THREAD

**Issue by vmitchell85** [tightenco/novapackages-issues#3]
It seems you're pulling the URL from the github user's profile but linking to novapackages.com otherwise. Which can be confusing since it seems to go nowhere if you're already on the main page.

**Comment by mattstauffer** [comment]
By that I think you mean "If a collaborator doesn't have  URL specified, it just links to "" which takes the user to novapackages.com", right? If so, we noticed that yesterday--thanks, good catch!

**Comment by vmitchell85** [comment]
Yep... I was just mousing over and seeing chrome show me the url... but upon further inspection the `href` is just `""`...

**Comment by mattstauffer** [comment]
Pushed a quick fix; for now it'll just send you to `#` (same page) if the author has no URL.
