### ISSUE TITLE
Expand popular section to 6 packages vs 3

### ISSUE THREAD

**Issue by dillingham** [tightenco/novapackages-issues#30]
![screenshot](https://user-images.githubusercontent.com/29180903/45578704-2eb0ca80-b851-11e8-92a1-bc29b1c94766.png)

fills up the empty space at the bottom

**Comment by dillingham** [comment]
I would also remove "See More" and rely on the All packages, ordered by recent
Or change "See More" to "See All Recent" and just link to that page

**Comment by mattstauffer** [comment]
The reason I split it out into 3 in each row was to increase the likelihood that anyone is aware there's both recent and popular as options.

However, I definitely get that that's not the concern with popular, only with recent. But then I sort of think it would be a bit weird for one to be show-3-hide-3 and the other to not be... so.. basically.. i don't know how best to handle this.

One way would be to figure out whether anyone actually uses the tag nav in the left.

**Comment by dillingham** [comment]
Yeah, Im just suggesting to extend the popular to fill empty space.
Recent gets more love, currently, with that top row and the view all option ordered by date. 
Popular deserves the extra row haha idk honestly just babbling 

I do think tags are valuable if they only showed tags with packages & counts per
Probably will need more soon: Localize & 3rd Party. Lots of packages for "intercom this" and "stripe that"

**Comment by mattstauffer** [comment]
Great points. Doing now. :)
