### ISSUE TITLE
Can login, but can't access my package

### ISSUE THREAD

**Issue by cendekia** [tightenco/novapackages-issues#33]
I don't know why I can't access my package today.

these are the errors:

![input email](https://i.imgur.com/z9d3ZVH.png)
![after submt email](https://i.imgur.com/C4OlfHG.png)

**Comment by ctroms** [comment]
Hey @cendekia! Sorry about that. This issue has been resolved. Thanks for your patience.

**Comment by cendekia** [comment]
@ctroms Thank you very much 👍
