### ISSUE TITLE
Sort Package Ideas By Reaction Count 

### ISSUE THREAD

**Issue by dillingham** [tightenco/novapackages-issues#34]
Would create a hierarchy and prioritization of more desired ideas.  😅

**Comment by mattstauffer** [comment]
How do you consider thumbs downs?

**Comment by dillingham** [comment]
Could subtract a thumbs up for every thumbs down. Negatives being sorted to the bottom. But I think naturally anything with thumbs up would go to the top regardless of thumbs down, none so far I think.

**Comment by mattstauffer** [comment]
Interesting idea!! :) Thanks for the suggestion; I've put it on the task list.
