### ISSUE TITLE
Feature Request: Package added date

### ISSUE THREAD

**Issue by ibrunotome** [tightenco/novapackages-issues#36]
Just a label showing when this package was added on the details

**Comment by ctroms** [comment]
Hey @ibrunotome,  We just want to clarify one thing before releasing this feature. By "when the package was added" are you referring to the date the package was added to NovaPackages or the date the package was added to packagist?

**Comment by ibrunotome** [comment]
The date the package was added to NovaPackages.

**Comment by mattstauffer** [comment]
Added (by @ctroms).
