### ISSUE TITLE
Feature Request: Search from everywhere (topbar)

### ISSUE THREAD

**Issue by ibrunotome** [tightenco/novapackages-issues#37]
It’s just put the “search packages" input of the home, into the navbar to search from anywhere on https://novapackages.com

**Comment by dillingham** [comment]
@ibrunotome is this different than the global search feature that exists currently?

**Comment by ibrunotome** [comment]
No, it’s just put the “search packages" input of the home, into the navbar to search from anywhere on https://novapackages.com

Bruno Tomé
https://github.com/ibrunotome

**Comment by mattstauffer** [comment]
Moved to https://github.com/tightenco/novapackages/issues
