### ISSUE TITLE
Check the version of packages more often

### ISSUE THREAD

**Issue by manogi** [tightenco/novapackages-issues#39]
It would be nice if the version of the packages would be checked more often. When I update my package to a new version this will show right away on packagist, but on novapackages.com it takes very long (a day?) until the version number is updated.

A button to manually check the version on the "edit package" page would be great, too.

**Comment by mattstauffer** [comment]
It checks them every 5 minutes, but I bet what you're running into is the fact that Packagist itself caches some of the data for twelve hours.

We can update our calls to use their second API which has a shorter cache period, but is apparently slower.

Would you do me a favor? Next time you notice your package seems out of date on NovaPackages.com, wait ten minutes, and if it's still out of date, check the Packagist API to see if it's also out of date:

https://packagist.org/packages/yourpackagevendor/yourpackagename.json

**Comment by manogi** [comment]
Here's my first report: right after updating the version from 0.2.0 to 0.2.1 it is showing on the packagist site, but not in the JSON feed you provided the URL for (and not on novapackages.com, of course).

**Comment by manogi** [comment]
Same result after an hour.
So this is because of the long caching in the Packagist API. 
Actually this is not such a big deal to me - I don't know how many people actually check the version on novapackages.com, when they run `composer update`  they will get the newest version anyway, so... I guess it is up to you if you want the versions to show up quicker or not.

Cheers Sebastian
