### ISSUE TITLE
Recently updated packages

### ISSUE THREAD

**Issue by devmsh** [tightenco/novapackages-issues#42]
Some packages are very helpful, but they are not ready to be used in early stage, so I feel that we need another sorting for the latest updated packages, so we can keep an eyes on them and give them another try?

**Comment by niladam** [comment]
That'd be a great option.

**Comment by rzv-me** [comment]
I would love that too

**Comment by bolechen** [comment]
+1

**Comment by tswonke** [comment]
+1

Yes, please! Shouldn't be difficult since this is all Laravel I guess! 😄

**Comment by mattstauffer** [comment]
Moved to https://github.com/tightenco/novapackages/issues
