### ISSUE TITLE
Rating value incorrectly formated on collaborator page

### ISSUE THREAD

**Issue by niladam** [tightenco/novapackages-issues#43]
I just noticed this while browsing[ a collaborators' page ](https://novapackages.com/collaborators/yassipad);

The rating is being displayed as `4.3333333333333` when it probably should be `4.3`

Screenshot attached

<img width="1243" alt="screenshot 2018-11-12 15 01 38" src="https://user-images.githubusercontent.com/4151765/48349091-e3b60680-e68b-11e8-820e-b5ef297adcd8.png">

**Comment by sariyana** [comment]
Hi, thanks for letting us know. We'll get this taken care of!

**Comment by sariyana** [comment]
This should be all taken care of now!
