### ISSUE TITLE
Screenshot from Github readme not displaying

### ISSUE THREAD

**Issue by nsaumini** [tightenco/novapackages-issues#44]
I have created new [package](https://novapackages.com/packages/saumini/ellipsis-textarea). When its displaying Readme from Github link it doesn't show the screenshot.

How to fix this?

![screen shot 2018-11-14 at 09 31 39](https://user-images.githubusercontent.com/12414016/48459479-56d88d80-e7f0-11e8-817c-0cb4f1e1c8a8.png)

**Comment by ctroms** [comment]
@nsaumini Thanks for reaching out. We are aware of this issue and will have a fix soon. Sorry for any inconvenience this may have caused.

**Comment by niladam** [comment]
@nsaumini The screenshot under screenshot is usually uploaded. If it's contained in your readme the URL to it should be changed from `./screenshot` to the actual URL of the image. Tired that already ?

**Comment by nsaumini** [comment]
@niladam I used relative path thats why it didn't work. Once I updated to full path, its working now. Thanks

**Comment by niladam** [comment]
@nsaumini glad you sorted it :)
