### ISSUE TITLE
Enhancement Request - Star Ratings

### ISSUE THREAD

**Issue by vootrunner** [tightenco/novapackages-issues#45]
Any chance of indicating the date of the last rating for a package (e.g. last rated 15-June-2001) under the rating count? Or perhaps something like "Last rated ** on 01-July-2016"

Packages still feel too much like a roll of the dice. Just bit by another 5 star rated package that just doesn't work.

**Comment by mattstauffer** [comment]
@vootrunner That's a really good request. I wish we had the number of reviews to make a "reviews this version" vs "reviews all time" etc., or a WordPress "compatibility with this version" kinda thing.

We'll think about this and try to find out if there are any useful ways to try to avoid this problem--thank you!

**Comment by mattstauffer** [comment]
Moved to https://github.com/tightenco/novapackages/issues
