### ISSUE TITLE
Basic profile css tweaks

### ISSUE THREAD

**Issue by dillingham** [tightenco/novapackages-issues#50]
to the section with image `h-48 w-48 border-4` the rounded works better with the logo

profile pic wrapper div
add `border-white rounded-full overflow-hidden mb-8`

package cards 
and add `p-8 border-grey` vs `p-4 border-grey-darker` to the package cards for more spacing like below

section headers wrapper
add `p-4 bg-grey-lightest mx-4`

![after](https://user-images.githubusercontent.com/29180903/51069042-4cbaeb80-15f5-11e9-8de8-df5d6b68dbab.png)

before

![before](https://user-images.githubusercontent.com/29180903/51069046-72e08b80-15f5-11e9-8765-6b5879f855ac.png)

**Comment by mattstauffer** [comment]
Done, with modifications. Thanks!!

**Comment by dillingham** [comment]
Thanks Matt!
