### ISSUE TITLE
Header Emoji Support

### ISSUE THREAD

**Issue by dillingham** [tightenco/novapackages-issues#51]
I know I know, you can't support every little thing :)

But some packages are using emjois and they arent being parsed.

https://novapackages.com/packages/dkulyk/nova-related-filter

`:rocket:` in the headline vs :rocket:

**Update** Issue seems to only be in the header
https://novapackages.com/packages/maatwebsite/laravel-nova-excel

`:rocket` is on that page also

**Comment by mattstauffer** [comment]
@dillingham I think what's happening is that our GitHub readme parser isn't converting the emoji. Great point! We'll have to figure out if there's a normalized tool for converting Slack/GitHub-style emoji over to real emoji.
