### ISSUE TITLE
add "See More" to Popular packages section of the homepage

### ISSUE THREAD

**Issue by alexagui** [tightenco/novapackages-issues#52]
I'd like to see an index page of all the Popular packages.

**Comment by bolechen** [comment]
+1

**Comment by rickmills** [comment]
Surprised this hasn't been added yet, being able to see the most popular packages (more than 6) would help find the most likely ones you're going to want/need to install. Without that its super hard to find widely used packages.

**Comment by mattstauffer** [comment]
Moved to https://github.com/tightenco/novapackages/issues
