### ISSUE TITLE
Markdown parser link bug

### ISSUE THREAD

**Issue by voidgraphics** [tightenco/novapackages-issues#54]
It seems the way your parse markdown in the readme files does not allow mailto links. At least that's what it looks like, I don't know for sure that it is the source of the problem.

You can see an example of this all the way at the bottom of [this readme](https://novapackages.com/packages/whitecube/nova-page).

The mailto link looks fine [on github](https://github.com/whitecube/nova-page/blob/master/README.md)

**Comment by andrewmile** [comment]
Mailto links now appear the same as they do on the github readme.
