### ISSUE TITLE
Sort by computed field [needs label: package-idea]

### ISSUE THREAD

**Issue by katieben** [tightenco/novapackages-issues#57]
Package idea: I'd love to be able to sort by computed field. Right now I'm just adding the field as a regular field, and periodically double-checking it (ew :). Anyone have a smarter idea?

**Comment by katieben** [comment]
I'm trying to label this as a package idea and I'm unsure how (maybe I don't have access)? FYI if someone can label this.

**Comment by mattstauffer** [comment]
@katieben If you add it as an issue here, @dillingham will add the label for you. :) Thanks!! Also.. BTW.. I would *love* this if it is technically possible...

https://github.com/tightenco/nova-package-development/issues
