### ISSUE TITLE
Nova Slider Package doesn't work in Nova v1.3.2

### ISSUE THREAD

**Issue by hanchenglu** [tightenco/novapackages-issues#58]
Laravel Version : 5.7
Nova Version : 1.3.2
PHP Version : 7.2
**Description**
I installed nova slider package in my nova via composer command, and then I defined a filter extending nova slider class.
But I faced this issue.
"Uncaught (in promise) TypeError: Cannot set property 'currentValue' of undefined in app.js"
I've been stuck on fixing this issue.
Some people say that I have to revert to 1.1.7 version.
Is it not possible to use this package in nova v1.3.2?
Thank you

**Comment by mattstauffer** [comment]
@hanchenglu this should go on the GitHub repo for the nova slider package.
