### ISSUE TITLE
README duplicating

### ISSUE THREAD

**Issue by LorenzoSapora** [tightenco/novapackages-issues#59]
Duplicate of the README sections (see: https://novapackages.com/packages/elevate-digital/nova-charcounted-fields).

I can't see where you'd be pulling this from, as both composer, and github, have the uptodate versions.

**Comment by mattstauffer** [comment]
@LorenzoSapora There are two sections of each page; the installation instructions and the readme.

The readme comes directly from version control. The installation instructions the author edits themselves.
