### ISSUE TITLE
Permission on role

### ISSUE THREAD

**Issue by inodesrl** [tightenco/novapackages-issues#60]
Hello,
I couldn't create an attached permission on a specific role.
When I click on "attach permission" on edit page of role , no permission shown in the combobox.

thanks, Marco.

**Comment by mattstauffer** [comment]
@inodesrl This repo is for issues about novapackages.com. If you'd like help with Nova, either check out the Laravel Discord and ask there, or, if it's a bug, their issue tracker: https://github.com/laravel/nova-issues/
