### ISSUE TITLE
I can't assign roles to more than two users

### ISSUE THREAD

**Issue by itafor** [tightenco/novapackages-issues#62]
After assigning roles to two users and i try to assign role to the third user i normally get this error

SQLSTATE[23000]: Integrity violation constraint : 1452 cannot add or update child row: a foreign key constraint fails

Pls, i need urgent help;
Thanks

**Comment by mattstauffer** [comment]
If anything this would fit https://github.com/laravel/nova-issues but i think it's likely better in Discord or StackOverflow.
