### ISSUE TITLE
Broken screenshots

### ISSUE THREAD

**Issue by JoshMoreno** [tightenco/novapackages-issues#64]
All the screenshots are broken. 

Here's a few packges to inspect:
- https://novapackages.com/packages/cdbeaton/boolean-tick
- https://novapackages.com/packages/codebykyle/calculated-field
- https://novapackages.com/packages/kirschbaum-development/nova-mail

**Comment by jakebathman** [comment]
Thanks so much Josh. I’ll take a look and see if I can’t get them resolving correctly.

**Comment by jakebathman** [comment]
Our wonderful @sariyana got screenshots up and visible again, thanks for the report Josh!
