### ISSUE TITLE
Details Pages don't load

### ISSUE THREAD

**Issue by wgmv** [tightenco/novapackages-issues#65]
Reproduce e.g. on [Package Details Page](https://novapackages.com/packages/optimistdigital/nova-translatable)

I see 2 console errors:

`app.js:1 TypeError: Cannot read property 'composer_name' of undefined`
`app.js:1 TypeError: Cannot read property 'name' of undefined`

I think yesterday the page worked fine, but today the details pages don't seem to load.

**Comment by damiani** [comment]
We were in the midst of an update when you noticed this; can you try that detail page again?

**Comment by wgmv** [comment]
I'm still seeing it in Opera, but not in firefox / edge. Earlier I only chcked Opera so it might be cached - but I did try to reload the app.js

**Comment by wgmv** [comment]
Seems fixed!
