### ISSUE TITLE
Persian Date Picker

### ISSUE THREAD

**Issue by bahirbarak** [tightenco/novapackages-issues#66]
Persian Date picker have a problem when we select a date for example( 2020-01-8) it add one date and show 2020-01-09 for persian date hope to solve this issue 
Date picker package link https://novapackages.com/packages/aloko/nova-persian-datepicker

**Comment by mattstauffer** [comment]
Hi @bahirbarak, this is not the place for individual packages' issues. Please visit the repo for that package.

**Comment by bahirbarak** [comment]
ok thank you
