### ISSUE TITLE
Add to rating stars with github stars & used by

### ISSUE THREAD

**Issue by LorenzoSapora** [tightenco/novapackages-issues#67]
Much like #45, the rating system is underused, and prone to initial gaming. I make a package, I 5 star it (or my puppet account does), and I have instant credibility.

If the cards included at least one of the metrics (used by, watch, star, fork), and possibly all of that information once on the package page itself, the ratings could be more authentic, at a glance.

**Comment by mattstauffer** [comment]
@LorenzoSapora Could you tell me a little bit more about what you mean by "credibility"? is it just how the star rating looks on the package itself? Or are there other pages that feel like they're being gamed?

I'm definitely interested in pulling in more Packagist data for validation, though! Let me take a look at that.

**Comment by mattstauffer** [comment]
![image](https://user-images.githubusercontent.com/151829/72563667-2967f380-387c-11ea-9636-a4240bb0ae88.png)

Easy-to-add were at least stars and downloads. Not sure if I want to try to cram those onto the cards though.

**Comment by LorenzoSapora** [comment]
By "credibility" I purely mean someone looking at the card view packages, would see 5 yellow stars, and skip over the light grey (1). Even the highest rated package on novapackages only has 44 stars, so it's not inconceivable to view 1-2 stars being classed as "good enough". 

Love the additions made to the package pages. Great job.

**Comment by mattstauffer** [comment]
Hm. I like to think we've all been conditioned to look at the number reviews by Amazon, right?

![image](https://user-images.githubusercontent.com/151829/72619774-07b64d00-390c-11ea-8045-b6501b1a476a.png)

![image](https://user-images.githubusercontent.com/151829/72619809-17ce2c80-390c-11ea-9e2e-4f24f3d8673c.png)

I do think we would do well to ban the author from rating it, but like you said, that still doesn't protect us from shell accounts.

**Comment by mattstauffer** [comment]
Moved to https://github.com/tightenco/novapackages/issues
