### ISSUE TITLE
Installation Instructions Markdown Error

### ISSUE THREAD

**Issue by naifalshaye** [tightenco/novapackages-issues#7]
I can't view or edit the package after it's been added anymore.

The <body> section just disappear due to an error that showing in console which says 
"env is not defined"

That's caused by the markdown content in the Installation Instructions textarea.

Because of the below line:
`<script src="https://maps.googleapis.com/maps/api/js?key={{env('ADDRESS_AUTOCOMPLETE_API_KEY')}}&libraries=places"></script>`

I can't view or edit or delete the package.
I can't add the package again with the same namespace/packagename

BR,
Naif

**Comment by naifalshaye** [comment]
Tested in Chrome & Firefox 

Problem has been solved by pausing script execution and removing the line from Installation Instructions that contains this code {{env('.

BR,
Naif

**Comment by mattstauffer** [comment]
This is fixed
